# models/staging/sources.yml

version: 2

sources:
  - name: raw
    description: "Raw data from uploaded CSV files."
    database: "{{ env_var('GCP_PROJECT') }}" # GCP project ID
    schema: ancient_gaming_raw
    tables:
      - name: affiliates
        description: "Affiliate origin data."
      - name: players
        description: "Player information."
      - name: transactions
        description: "Player transaction data."
